### ISSUE TITLE
Default namespaces generates problem

### ISSUE THREAD

**Issue by ihedvall** [gittiver/libexpatpp#6]
I get errors if an XML tag includes a default namespace declaration as below.
`<Root xmlns='http://www.asam.net/mdf/v4/'>`
If the tag define the namespace as `xmlns:h='...'`, everything works OK.

A hint  or a temporary solution is to change the parser constructor to use` XML_ParserCreate_MM("UTF-8", nullptr, nullptr)` instead of the current `XML_ParserCreateNS("UTF8", ':')`

**Comment by gittiver** [comment]
Could you send a sample file where I can check if bug is fixed? 
And sorry, that it takes that long, I simply overlook the request as I was not very active on this project currently.

**Comment by ihedvall** [comment]
GitHub cannot append XML files of some reason but the below XML snippet should work as a verification.
`
<HDcomment xmlns="http://www.asam.net/mdf/v4">
    <TX>ASAM MDF 4.0 Example file created by ETAS. Contents: 2 simple channel groups containing ints and floats in
        little endian format.
    </TX>
    <time_source>PC timer</time_source>
    <common_properties>
        <e name="subject">Example</e>
        <e name="project">ASAM Example Files</e>
        <e name="department">ETAS GmbH</e>
        <e name="author">Tobias Langner</e>
    </common_properties>
</HDcomment>
`

**Comment by gittiver** [comment]
hmm, maybe because header \<?xml version="1.0" encoding="UTF-8"?\> is missing, I will setup a test case for the sample, with and without it.

**Comment by gittiver** [comment]
I added a test to sources with the fragment above, as expected it returns namespace and element name separated by ":", means for the fragment the elementnames:
    "http://www.asam.net/mdf/v4:HDcomment",
    "http://www.asam.net/mdf/v4:TX",
    "http://www.asam.net/mdf/v4:time_source",
    "http://www.asam.net/mdf/v4:common_properties",
    "http://www.asam.net/mdf/v4:e",
    "http://www.asam.net/mdf/v4:e",
    "http://www.asam.net/mdf/v4:e",
    "http://www.asam.net/mdf/v4:e",

see test https://github.com/gittiver/libexpatpp/blob/main/test/test_asam_generation_problem.cpp

**Comment by gittiver** [comment]
will close the issue. maybe a problem with documentation?
if something is missing, feel free to reopen.
